apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dzc9lu6nf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dzc9lu6nf-python 
  name: dzc9lu6nf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dzc9lu6nf-python 
